chore(backport): autocollapse release notes (#1145) (#1147)
<!-- markdownlint-disable MD041 -->
#### What this PR does / why we need it

Adds a small script that autocollapses our release notes again because
we no longer use release drafter

Backported to allow the release notes to be drafted correctly.

#### Which issue(s) this PR fixes
<!--
Usage: `Fixes #<issue number>`, or `Fixes (paste link of issue)`. -->

Co-authored-by: Frederic Wilhelm <frederic.wilhelm@sap.com>

diff --git a/.github/workflows/release-drafter.yaml b/.github/workflows/release-drafter.yaml
--- a/.github/workflows/release-drafter.yaml
+++ b/.github/workflows/release-drafter.yaml
@@ -44,6 +44,7 @@ jobs:
           fetch-tags: true
       - name: Setup Release with gh
         env:
+          COLLAPSE_THRESHOLD: 5
           REF: ${{ github.ref }}
           REPO: ${{ github.repository }}
           GH_TOKEN: ${{ steps.generate_token.outputs.token }}
@@ -81,15 +82,25 @@ jobs:
                -q .body \
              )
           
+          if [[ -z $notes ]]; then
+            echo "No release notes generated from API, failed"
+            exit 1
+          fi
+          
+          echo "Auto-Collapsing release notes to reduce size"
+          printf "%s\n" "$notes" > $RUNNER_TEMP/release_notes.md
+          bash hack/collapse/auto_collapse.sh $RUNNER_TEMP/release_notes.md $RUNNER_TEMP/release_notes_processed.md ${{ env.COLLAPSE_THRESHOLD }}
+          notes=$(cat $RUNNER_TEMP/release_notes_processed.md)
+          
           echo "Release Notes generated for ${{env.RELEASE_VERSION}}:"
-          echo "${notes}"
+          printf "%s\n" "$notes"
           
           echo "Verifying if release ${{env.RELEASE_VERSION}} already exists"
           if [[ -z $(gh release list -R ${REPO} --json name -q '.[] | select(.name == "${{env.RELEASE_VERSION}}")') ]]; then
             echo "Release ${{env.RELEASE_VERSION}} does not exist yet, creating from scratch"
             gh release create ${{env.RELEASE_VERSION}} \
               --title "${{env.RELEASE_VERSION}}" \
-              --notes "${notes}" \
+              --notes "$(printf "%s\n" "$notes")" \
               --draft \
               --latest=false \
               --target ${{ github.ref }} \
