Update retrigger-publish-to-other.yaml

diff --git a/.github/workflows/retrigger-publish-to-other.yaml b/.github/workflows/retrigger-publish-to-other.yaml
--- a/.github/workflows/retrigger-publish-to-other.yaml
+++ b/.github/workflows/retrigger-publish-to-other.yaml
@@ -47,8 +47,14 @@ jobs:
         fi
         # let's check if the version is already published
         curl -sSL -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ steps.generate_token.outputs.token }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/open-component-model/ocm/releases > releases.json
-        jq -r '.[] | .tag_name' releases.json > versions.txt
-        grep -Fxq '${{ github.event.inputs.version }}' versions.txt && echo "Version (${{ github.event.inputs.version }}) found" || echo "Version (${{ github.event.inputs.version }}) not found!" && cat versions.txt && exit 1
+        jq -r '.[] | .tag_name' releases.json | grep -v -E '.*-rc|latest' > versions.txt
+        if grep -Fxq '${{ github.event.inputs.version }}' versions.txt; then
+          echo "Version (${{ github.event.inputs.version }}) found!"
+        else
+          echo "Version (${{ github.event.inputs.version }}) not found! This are the availble ones:"
+          cat versions.txt
+          exit 1
+        fi
         echo "RELEASE_VERSION=$(echo ${{ github.event.inputs.version }} )" >> $GITHUB_ENV
     - name: Publish Event
       uses: peter-evans/repository-dispatch@v3
